plugins {
    id "com.android.application"
}

android {
    namespace "com.bitbarista.k7controller"
    compileSdk 35

    defaultConfig {
        applicationId "com.bitbarista.k7controller"
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName "0.2.0"
    }

    applicationVariants.configureEach { variant ->
        variant.outputs.configureEach {
            outputFileName = "K7-Controller-v${variant.versionName}.apk"
        }
    }
}
