plugins {
    id "com.android.application"
}

android {
    namespace "com.bitbarista.k7controller"
    compileSdk 35

    defaultConfig {
        applicationId "com.bitbarista.k7controller"
        minSdk 23
        targetSdk 35
        versionCode 11
        versionName "0.2.9"
    }

    buildFeatures {
        buildConfig true
    }

    applicationVariants.configureEach { variant ->
        variant.outputs.configureEach {
            outputFileName = "K7-Controller-v${variant.versionName}.apk"
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
}
